feat: Monitoring kafka integration
goto/stencil pull request #18
Opened 2024-04-02 03:25 UTC by Vaishnavi190900

Added metrics related to kafka messages success an failures using statsd exporter and prometheus.

2024-04-02 12:36 UTC, rajuGT requested changes

2024-04-02 12:36 UTC, rajuGT commented on config/config.go
> +type ProducerConfig struct {
MetricProducerConfig ?

2024-04-02 12:36 UTC, rajuGT commented on config/config.yaml
> +producer:
metric_producer?

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +		log.Printf("failed to create producer: %w", err)
to address the github mentioned error below, use `%s` and param err.Error()

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +func (kp *KafkaProducer) ProduceMessages(topic string, protoMessage proto.Message, statsdClient statsd.Statter) error {
Name this method as ProduceMessageWithRetries and accept the retry and retryInterval as parameters.

Move code from line44 to line81 and make a method `func (kp *kafkaProducer) ProduceMessages.

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +func (kp *KafkaProducer) ProduceMessages(topic string, protoMessage proto.Message, statsdClient statsd.Statter) error {
Should we call Produce or Push?

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +			fmt.Printf("failed to produce message (attempt %d/%d): %v\n", i, maxRetries, err)
remove fmt, it should be log

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +			fmt.Printf("delivery failed (attempt %d/%d): %v\n", i, maxRetries, m.TopicPartition.Error)
remove fmt, it should be log

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +			return err
Failed to send metrics shouldn't stop the business flow, you can log this error and ignore, i.e. no need to return err.

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +			return err
Failed to send metrics shouldn't stop the business flow, you can log this error and ignore, i.e. no need to return err.

2024-04-02 12:36 UTC, rajuGT commented on kafkaIntegration/producer.go
> +		err := statsdClient.Gauge("kafka_integration.latency", latency.Milliseconds(), 1)
define these constants as const "kafka_integration.latency"

2024-04-03 14:56 UTC, rajuGT commented on config/config.go
> +type ProducerConfig struct {
rename it as KafkaProducerConfig

2024-04-03 14:57 UTC, rajuGT commented on config/config.go
> +	Producer      ProducerConfig
KafkaProducer

2024-04-03 14:57 UTC, rajuGT commented on config/config.yaml
> +producer:
kafka_producer

2024-04-03 15:08 UTC, rajuGT commented on kafkaIntegration/monitoring.go
> +package kafkaIntegration
make a package changeEventProducer and inside that lets have package kafka.

2024-04-03 15:16 UTC, rajuGT commented on kafkaIntegration/producer.go
> +	for i := 1; i <= retries; i++ {
prefer starting with zero

2024-04-08 10:37 UTC, manigandand commented on changeEventProducer/kafka/producer.go
> +	}
plz validate the typecast with ok flag to make sure we don't panic upon unsupported types.

```suggestion
	if m, ok := deliveryReport.(*kafka.Message); ok && m.TopicPartition.Error != nil {
		log.Printf(err.Error())
		return err
	}
```

2024-04-08 10:55 UTC, manigandand requested changes
please make these changes

2024-04-08 11:07 UTC, manigandand approved these changes
Please resolve the lint issue @Vaishnavi190900

2024-04-08 12:07 UTC, manigandand requested changes
Please resolve the lint issue and merge conflicts @Vaishnavi190900

2024-04-08 14:12 UTC, Vaishnavi190900 commented
@rajuGT @manigandand resolved all the comments and checks are also passed. Can you please review and approve?

2024-04-08 14:31 UTC, manigandand commented
LGTM

2024-04-08 15:40 UTC, manigandand approved these changes

2024-04-09 09:28 UTC, rajuGT requested changes

2024-04-09 09:28 UTC, rajuGT commented on changeEventProducer/kafka/producer.go
> +			time.Sleep(retryInterval)
can we increase the failurecount metric here?

2024-04-09 09:28 UTC, rajuGT commented on changeEventProducer/kafka/producer.go
> +		return fmt.Errorf("failed to marshal Protobuf message: %v", err)
%s, err.Error()

2024-04-10 07:43 UTC, rajuGT approved these changes

2024-04-10 09:08 UTC, merged