feat: kafka library changed
goto/stencil pull request #26
Opened 2024-04-22 13:54 UTC by Vaishnavi190900

Moving kafka implementation from confluentic-kafka to segmentio-kafka.

2024-04-22 17:47 UTC, sbchaos approved these changes

2024-04-23 10:03 UTC, gdgagan696 requested changes

2024-04-23 10:03 UTC, gdgagan696 commented on changeEventProducer/kafka/writer.go
> +	err := w.kafkaWriter.WriteMessages(context.Background(), message)
will it take care of retries on its own?

2024-04-23 10:03 UTC, gdgagan696 commented on core/schema/service.go
> +		return err
can we use fmt.Errorf("unable to push message to Kafka topic %s for schema change event %s: %s", schemaChangeTopic, sce, err.Error())

2024-04-23 10:03 UTC, gdgagan696 commented on changeEventProducer/kafka/writer.go
> +	"fmt"
please remove kafka configs which are not being used.

2024-04-23 10:05 UTC, Vaishnavi190900 commented on changeEventProducer/kafka/writer.go
> +	err := w.kafkaWriter.WriteMessages(context.Background(), message)
yes, while creating Kafka writer, there is a config called MaxAttempts, which will take care of the retries.

2024-04-23 10:28 UTC, gdgagan696 approved these changes

2024-04-23 10:33 UTC, merged